version: "3"
services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: front
    volumes:
      - ./front:/usr/src/app/front
      - /usr/src/app/front/node_modules
